name: ecommerce_app_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_screenutil: 
  dots_indicator:
  smooth_page_indicator: ^1.1.0
  intl:
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/
  - assets/images/

include: package:flutter_lints/flutter.yaml

linter:
  rules:
      prefer_const_constructors: false;